# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            PHONEMeS
tagline:          Phosphorylation Networks for Mass Spectrometry
description:      "Method to model signaling networks based on untargeted phosphoproteomics data"
#url:              https://github.com/saezlab/PHONEMeS
baseurl:          /PHONEMeS/
toollogo:         /PHONEMeS/public/logo.jpeg

author:
  name:           'Jakob Wirbel'

paginate:         5

# Custom vars
version:          0.2.7

github:
  repo:           https://github.com/saezlab/PHONEMeS
